---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.qinkeith.com
  resources:
  - timeseriesdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.qinkeith.com
  resources:
  - timeseriesdbs/finalizers
  verbs:
  - update
- apiGroups:
  - operator.qinkeith.com
  resources:
  - timeseriesdbs/status
  verbs:
  - get
  - patch
  - update
