# permissions for end users to view timeseriesdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: timeseriesdb-viewer-role
rules:
- apiGroups:
  - operator.qinkeith.com
  resources:
  - timeseriesdbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.qinkeith.com
  resources:
  - timeseriesdbs/status
  verbs:
  - get
