name: Go

env:
  BUILD_DIR: nginx-operator
  
on:
  push:
    branches: [ "main" ]
    paths:
      - $BUILD_DIR/**
  pull_request:
    branches: [ "main" ]
    paths:
      - $BUILD_DIR/**

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./$BUILD_DIR

    - name: Test
      run: go test -v ./$BUILD_DIR
